apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.petclinic.deploymentName }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.petclinic.appName }} 
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.petclinic.appName }} 
    spec:
      containers:
        - name: {{ .Values.petclinic.container.name }} 
          image: {{ .Values.petclinic.container.image }}
          imagePullPolicy: {{ .Values.petclinic.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.petclinic.port }}
          env:  
            - name: POSTGRES_PASSWORD
              value: petclinic
            - name: POSTGRES_USER
              value: petclinic
            - name: POSTGRES_DB
              value: petclinic




